"""Neural transducer baseline wrapper for the new system."""
import os
import sys
import subprocess
import re
from pathlib import Path
from typing import Dict, Any

from ..utils import ensure_dir, resolve_path
from ..utils.save_results import save_neural_results
from ..data import load_data
from ..utils.evaluation import evaluate_forward


class NeuralBaselineModel:
    """
    Neural transducer baseline model wrapper.
    
    Uses the SIGMORPHON 2023 training script (task0-trm.sh) to train
    a transformer-based neural transducer model.
    """
    
    def __init__(self, config, lang_config, mode='train'):
        """
        Initialize neural baseline.
        
        Args:
            config: Model configuration dict
            lang_config: Language configuration dict
            mode: 'train' or 'predict'
        """
        self.config = config
        self.lang_config = lang_config
        self.mode = mode
        self.lang_code = lang_config['language']['code']
        
        # Get baseline directory path
        project_root = Path(__file__).parent.parent.parent
        self.baseline_dir = project_root / 'baselines' / 'neural' / 'neural-transducer-master'
        self.train_script = self.baseline_dir / 'src' / 'train.py'
        
        # Checkpoint directory where models will be saved
        self.checkpoint_dir = self.baseline_dir / 'checkpoints' / 'sig23' / 'tagtransformer'
        
        if not self.baseline_dir.exists():
            raise FileNotFoundError(f"Neural baseline directory not found: {self.baseline_dir}")
        
        # Get output directory for saving results in new system
        output_template = config.get('output_dir_template', 'results/neural-baseline-{lang}')
        self.output_dir = output_template.format(lang=self.lang_code)
        ensure_dir(self.output_dir)
        
        # Determine data source (always use unimorph for neural baseline)
        self.data_source = 'unimorph'
    
    def train(self):
        """
        Train the model using SIGMORPHON 2023 shell script.
        
        Simply runs the task0-trm.sh script with the language code.
        """
        print(f"\n{'='*60}")
        print(f"Training neural baseline for {self.lang_code}")
        print(f"Using SIGMORPHON 2023 configuration (task0-trm.sh)")
        print(f"{'='*60}")
        
        # Path to the SIGMORPHON 2023 shell script
        script_path = self.baseline_dir / 'example' / 'sigmorphon2023-shared-tasks' / 'task0-trm.sh'
        
        if not script_path.exists():
            raise FileNotFoundError(f"SIGMORPHON 2023 script not found: {script_path}")
        
        # Run the shell script with language parameter
        cmd = ['bash', str(script_path), self.lang_code]
        
        print(f"Running: bash {script_path.name} {self.lang_code}")
        print("This may take 10-30 minutes depending on your hardware...")
        
        # Ensure checkpoint directory exists
        ensure_dir(str(self.checkpoint_dir))
        
        # Run training
        result = subprocess.run(
            cmd,
            cwd=str(self.baseline_dir),
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            print(f"Training failed:")
            print(result.stderr)
            raise RuntimeError("Neural baseline training failed")
        
        # Print output
        print(result.stdout)
        if result.stderr:
            print(result.stderr)
        
        print(f"\nTraining completed successfully")
        print(f"Model saved to {self.checkpoint_dir / self.lang_code}")
        
        return str(self.checkpoint_dir)
    
    def predict(self, checkpoint=None):
        """
        Evaluate the trained model on test set.
        
        The train.py script automatically generates predictions during training,
        so we just need to load and evaluate them. If predictions don't exist but
        checkpoints do, try to regenerate them.
        
        Args:
            checkpoint: Specific checkpoint to load (not used)
            
        Returns:
            Dictionary with test metrics
        """
        print(f"\n{'='*60}")
        print(f"Evaluating neural baseline for {self.lang_code}")
        print(f"{'='*60}")
        
        # Predictions file generated by train.py
        predictions_file = self.checkpoint_dir / f"{self.lang_code}.decode.test.tsv"
        
        if not predictions_file.exists():
            # Check if checkpoints exist - maybe training completed but decode step failed
            checkpoint_files = list(self.checkpoint_dir.glob(f"{self.lang_code}.nll_*.epoch_*"))
            
            if checkpoint_files:
                print(f"Found {len(checkpoint_files)} checkpoints but no decode file.")
                print(f"Training may have been interrupted. Please retrain to generate predictions:")
                print(f"  python run.py --model neural --language {self.lang_code} --train --predict")
            else:
                print(f"No checkpoints found for {self.lang_code}.")
                print(f"Please run training first:")
                print(f"  python run.py --model neural --language {self.lang_code} --train --predict")
            
            raise FileNotFoundError(
                f"No predictions found for {self.lang_code} at {predictions_file}"
            )
        
        print(f"Using predictions from: {predictions_file}")
        
        # Get test data path
        data_config = self.lang_config['data']
        data_source_cfg = data_config.get(self.data_source, data_config['unimorph'])
        test_file = resolve_path(data_source_cfg['test'])
        
        # Load test data and predictions
        print("Loading test data and predictions...")
        test_data = load_data(test_file, has_context=False)
        
        # Read predictions (TSV format: lemma\tfeatures\tpredicted_form)
        predictions = []
        with open(predictions_file, 'r', encoding='utf-8') as f:
            for i, line in enumerate(f):
                line = line.strip()
                if not line:  # Skip empty lines
                    continue
                if i == 0 and line.startswith('prediction'):  # Skip header line
                    continue
                parts = line.split('\t')
                if len(parts) >= 2:
                    # The prediction is space-separated characters, need to join them
                    pred_text = parts[0].replace(' ', '')
                    predictions.append(pred_text)
                else:
                    predictions.append('')  # empty prediction for malformed lines
        
        # Extract gold forms (test_data is list of tuples: (lemma, features, form))
        gold_forms = [item[2] for item in test_data]
        
        # Ensure predictions match test set size
        if len(predictions) != len(gold_forms):
            raise ValueError(
                f"Prediction count ({len(predictions)}) doesn't match test set size ({len(gold_forms)})\n"
                f"This might indicate a data mismatch. Please retrain the model."
            )
        
        # Evaluate forward direction (inflection)
        print("Evaluating predictions...")
        test_metrics = evaluate_forward(predictions, gold_forms)
        
        print(f"Test Accuracy: {test_metrics['accuracy']:.4f}")
        print(f"Mean Levenshtein: {test_metrics['mean_levenshtein']:.4f}")
        print(f"Correct: {test_metrics['correct']}/{test_metrics['total']}")
        
        # Save results
        print("Saving results...")
        save_neural_results(
            output_dir=self.output_dir,
            model_name=self.config.get('name', 'neural'),
            language=self.lang_code,
            test_metrics=test_metrics,
            config={
                'epochs': 'max_steps:20000',  # SIGMORPHON 2023 uses max_steps instead
                'batch_size': 400,  # From SIGMORPHON 2023 config
                'learning_rate': 0.001,  # From SIGMORPHON 2023 config
            }
        )
        
        return test_metrics
